package com.elt.loanapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer amount;
	private java.lang.String loanApplicationStatus;
	private java.lang.String accountType;

	private java.lang.Integer loanAmount;

	public LoanApplication() {
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.lang.String getLoanApplicationStatus() {
		return this.loanApplicationStatus;
	}

	public void setLoanApplicationStatus(java.lang.String loanApplicationStatus) {
		this.loanApplicationStatus = loanApplicationStatus;
	}

	public java.lang.String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(java.lang.String accountType) {
		this.accountType = accountType;
	}

	public java.lang.Integer getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(java.lang.Integer loanAmount) {
		this.loanAmount = loanAmount;
	}

	public LoanApplication(java.lang.Integer amount,
			java.lang.String loanApplicationStatus,
			java.lang.String accountType, java.lang.Integer loanAmount) {
		this.amount = amount;
		this.loanApplicationStatus = loanApplicationStatus;
		this.accountType = accountType;
		this.loanAmount = loanAmount;
	}

}